# Candace Savonen May 2023

name: Accept invites

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:

  accept-invites:
    name: Accept Invites
    runs-on: ubuntu-latest
    container:
      image: r-base

    steps:

    - name: Install githelpers
      run: Rscript -e "Sys.setenv(GITHUB_PAT = '${{secrets.GH_PAT}}'); devtools::install_github('fhdasl/githubhelpers')"

    - name: Run the thing
      run: Rscript "accept_all_invites(git_pat = '${{secrets.GH_PAT}}')"
